Talks/vslive-2015/Pollster/App/src/PollWebFrontend/Models/PollCreatorViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Pollster.CommonCode;

namespace Pollster.PollWebFrontend.Models
{
    public class PollCreatorViewModel
    {
        public string Title { get; set; }
        public string Question { get; set; }
        public string AuthorEmail { get; set; }
        public string Options { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndDate { get; set; }
        public DateTime EndTime { get; set; }
    }


    public class PollConfirmationViewModel
    {
        public string Title { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }

        public bool Success { get; set; }
        public string ErrorMessage { get; set; }
    }
}

Talks/vslive-2015/Pollster/App/src/PollWebFrontend/Models/PollFeedViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Pollster.CommonCode;

namespace Pollster.PollWebFrontend.Models
{
    public class IndexPollFeedViewModel
    {
        public IList<PollDefinition> Polls { get; set; }
    }

    public class SubmittedVoteViewModel
    {
        public string PollId { get; set; }

        public string VotedOptionId { get; set; }
        public Dictionary<string, int> LatestVotes { get; set; }

        public bool Success { get; set; }

        public string ErrorMessage { get; set; }

    }
}

Talks/vslive-2015/Pollster/App/src/PollWebFrontend/Controllers/HealthCheckController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;

namespace Pollster.PollWebFrontend.Controllers
{
    [Route("api/[controller]")]
    public class HealthCheckController : Controller
    {
        [HttpGet]
        public string Get()
        {
            return "PollWebFrontend";
        }
    }
}

Talks/vslive-2015/Pollster/App/src/PollWebFrontend/Controllers/PollCreatorController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;

using Pollster.CommonCode;

using Pollster.PollWebFrontend.Clients;
using Pollster.PollWebFrontend.Models;

namespace Pollster.PollWebFrontend.Controllers
{
    public class PollCreatorController : Controller
    {
        IPollWriter _pollWriter;

        public PollCreatorController(IPollWriter writer)
        {
            this._pollWriter = writer;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var model = new PollCreatorViewModel
            {
                StartDate = DateTime.Today,
                EndDate = DateTime.Today.AddDays(1)
            };

            model.StartTime = DateTime.Now.AddMinutes(10);
            model.EndTime = DateTime.Now.AddMinutes(10);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Index(PollCreatorViewModel model)
        {
            PollConfirmationViewModel confirmModel = new PollConfirmationViewModel();
            try
            {
                var pollDefinition = new PollDefinition
                {
                    Title = model.Title,
                    Question = model.Question,
                    AuthorEmail = model.AuthorEmail,
                    Options = new Dictionary<string, PollDefinition.Option>()
                };
                pollDefinition.StartTime = model.StartDate.Date.Add(model.StartTime.TimeOfDay);
                pollDefinition.EndTime = model.EndDate.Date.Add(model.EndTime.TimeOfDay);

                string line;
                using (var reader = new StringReader(model.Options))
                {
                    int index = 0;
                    while ((line = reader.ReadLine()) != null)
                    {
                        pollDefinition.Options.Add(index.ToString(), new PollDefinition.Option { Text = line });
                        index++;
                    }
                }

                await this._pollWriter.Save(pollDefinition);

                confirmModel.Title = pollDefinition.Title;
                confirmModel.StartTime = pollDefinition.StartTime;
                confirmModel.EndTime = pollDefinition.EndTime;
                confirmModel.Success = true;
            }
            catch(Exception e)
            {
                confirmModel.Success = false;
                confirmModel.ErrorMessage = string.Format("Unknown error saving poll: {0}", e.Message);
            }

            return View("Confirmation", confirmModel);
        }
    }
}

Talks/vslive-2015/Pollster/App/src/PollWebFrontend/Controllers/PollFeedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;

using Pollster.PollWebFrontend.Models;
using Pollster.PollWebFrontend.Clients;

namespace Pollster.PollWebFrontend.Controllers
{
    public class PollFeedController : Controller
    {
        IPollFeed _pollFeed;
        IPollVoter _pollVoter;

        public PollFeedController(IPollFeed pollFeed, IPollVoter pollVoter)
        {
            this._pollFeed = pollFeed;
            this._pollVoter = pollVoter;
        }

        public async Task<IActionResult> Index(IndexPollFeedViewModel model)
        {
            model.Polls = await this._pollFeed.GetFeed();
            return View(model);
        }

        [HttpPost]
        public async Task<JsonResult> SubmittedVote(string pollId, string optionId)
        {
            var model = new SubmittedVoteViewModel
            {
                PollId = pollId,
                VotedOptionId = optionId
            };
            try
            {
                model.LatestVotes = await this._pollVoter.SubmitVote(pollId, optionId);
                model.Success = true;
            }
            catch(Exception e)
            {
                model.Success = false;
                model.ErrorMessage = Pollster.CommonCode.Utilities.FormatInnerException(e);
            }

            var result = new JsonResult(model);
            return result;
        }
    }
}

Talks/vslive-2015/Pollster/App/src/PollWebFrontend/Views/PollCreator/Confirmation.cshtml
@model PollConfirmationViewModel

@{

    ViewData["Title"] = "Poll Created";
}

@if (Model.Success)
{
    <h2>Poll Created!!!</h2>

    <text>Your poll <b>@(Model.Title)</b> has been created and scheduled to go live at <b>@(Model.StartTime)</b> till <b>@(Model.EndTime)</b>.</text>
}
else {
    <h2>Poll failed to be created!!!</h2>

    <text>Error Message: @(Model.ErrorMessage)</text>
}

Talks/vslive-2015/Pollster/App/src/PollWebFrontend/Views/PollCreator/Index.cshtml
@model PollCreatorViewModel

@{

    ViewData["Title"] = "Create Poll";
}


<div class="borderedpanel">
    @using (Html.BeginForm())
    {
        <fieldset>
            <h2>Create a Poll</h2>

            <div class="pollform">
                <div class="editor-label">
                    @Html.LabelFor(model => model.AuthorEmail, "Email")
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.AuthorEmail)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Title)
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.Title)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Question)
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.Question, new { style = "width:500px;" })
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Options, "Poll Options")
                </div>
                <div class="editor-field">
                    @Html.TextAreaFor(model => model.Options, new { style = "width:500px;", rows = "10" })
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.StartTime, "Starts At")
                </div>
                <div class="editor-field">
                    @Html.TextBox("StartDate", Model.StartDate.ToString("MM/dd/yyyy"), new { @class = "date" })
                    @Html.TextBox("StartTime", Model.StartTime.ToString("HH:mm"))
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.EndTime, "Ends At")
                </div>
                <div class="editor-field">
                    @Html.TextBox("EndDate", Model.EndDate.ToString("MM/dd/yyyy"), new { @class = "date" })
                    @Html.TextBox("EndTime", Model.EndTime.ToString("HH:mm"))
                </div>

                <input type="submit" value="Create Poll" class="pollcreate" />
            </div>
        </fieldset>
    }
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('.date').datepicker({ dateFormat: "dd/mm/yy" });
    });
</script>

Talks/vslive-2015/Pollster/App/src/PollWebFrontend/Views/PollFeed/Index.cshtml
@model IndexPollFeedViewModel

@{
    ViewData["Title"] = "Current Poll Feed";
}


@foreach (var poll in Model.Polls.OrderByDescending(x => x.StartTime))
{
    <div class="borderedpanel">
        <h2>@(poll.Title)</h2>
        <div class="pollquestion">@(poll.Question)</div>
        <p>
            <ul id="@(poll.Id)">
                @foreach (var option in poll.Options.OrderBy(x => x.Key))
                {
                    <li class="polloption"><input type="radio" name="@(poll.Id)" value="@option.Key" />&nbsp;@option.Value.Text</li>
        }
            </ul>
        </p>
        <button id="@(poll.Id)" onclick="onSubmitVote('@(poll.Id)')">Vote!</button>

    </div>
}

<script type="text/javascript">


    var model = @Html.Raw(Json.Serialize(Model));



    function onSubmitVote(pollId)
    {
        var checkedOption = document.querySelector('input[name="'+pollId+'"]:checked');
        if (checkedOption === null) {
            alert('You must select a choice before voting')
            return;
        }

        var optionId = checkedOption.value;

        $.ajax({
        type: "POST",
            url: "@Url.Action("SubmittedVote", "PollFeed")/?pollId=" + pollId + "&optionId=" + optionId,
            dataType: "json",
            contentType: "application/json; charset=utf-8",
            success: successFunc,
            error: errorFunc
        })
    }

    function successFunc(data, status) {
        if (data.Success) {

            // Find the existing poll so we can find the text of the poll options
            var selectedPoll = null;
            for (index = 0; index < model.Polls.length; ++index) {
                if(model.Polls[index].Id == data.PollId) {
                    selectedPoll = model.Polls[index];
                    break;
                }
            }

            if(selectedPoll != null) {
                var button = $("button[id='"+ data.PollId +"']");
                button.attr("disabled","disabled");

                var parent = $("ul[id='"+ data.PollId +"']");

                parent.empty();

                for(var optionId in sortObjectByKey(data.LatestVotes)){
                    var votes = data.LatestVotes[optionId];

                    var message = selectedPoll.Options[optionId].Text + ": " + votes;
                    var li = $('<li class="polloption">' + message + '</li>')
                        .appendTo(parent);
                }
            }
        }
        else {
            alert(data.ErrorMessage);
        }
    }

    function errorFunc() {
        alert('error');
    }

    function sortObjectByKey(obj){
        var keys = [];
        var sorted_obj = {};

        for(var key in obj){
            if(obj.hasOwnProperty(key)){
                keys.push(key);
            }
        }

        // sort keys
        keys.sort();

        // create new array based on Sorted Keys
        jQuery.each(keys, function(i, key){
            sorted_obj[key] = obj[key];
        });

        return sorted_obj;
    };
</script>

Talks/vslive-2015/Pollster/App/src/PollWebFrontend/Views/Shared/_Layout.cshtml
@{
    ViewData["Title"] = "Current Poll Feed";
    string servedFrom = "development";

    //var aspnetEnv = Environment.GetEnvironmentVariable("ASPNET_ENV");
    //switch (aspnetEnv.ToLower())
    //{
    //    case "elasticbeanstalk-docker":
    //        servedFrom = "Docker and AWS Elastic Beanstalk";
    //        break;

    //    case "codedeploy":
    //        servedFrom = "Windows/IIS and AWS CodeDeploy";
    //        break;

    //    case "ecs-docker":
    //        servedFrom = "Docker and Amazon EC2 Container Service";
    //        break;

    //    case "default":
    //        break;
    //}

}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - Pollster</title>

        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-controller="PollFeed" asp-action="Index">Polls</a></li>
                        <li><a asp-controller="PollCreator" asp-action="Index">Create</a></li>
                    </ul>
                    <div id="servedfrom">This page served from @servedFrom</div>
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p id="copyright">&copy; 2015 - Pollster</p>
            </footer>
        </div>

        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/hammer.js/hammer.js"></script>

        @RenderSection("scripts", required: false)
    </body>
</html>